### ISSUE TITLE
Nexus upload?

### ISSUE THREAD

**Issue by ofek256** [MissCorruption/QuickLootEE-NG#5]
Hey, just saw this fork and I think you can definitely upload this to the Nexus!
The original is published under MIT license, so you should be able to just upload this in its entirety without having to require the old version to be installed.

**Comment by MissCorruption** [comment]
Given that the original author has been MIA I might upload this to Nexus. I'd need to patch a lot of UI mods though, given the LootMenu changes from Parapets PR

**Comment by MissCorruption** [comment]
Done, it's [here](https://www.nexusmods.com/skyrimspecialedition/mods/120075)!
